<a href="https://colab.research.google.com/github/Cr1mson901/IntroToPyTorch/blob/main/00_pytorchfundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##00.Pytorch fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


##Introduction to tensors
Creating tensors
# Scalar
https://pytorch.org/docs/stable/tensors.html

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.size(
)

torch.Size([1, 3, 3])

In [ ]:
TENSOR = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,1,2,3]],[[4,5,6,7],[9,0,3,2],[3,3,5,3]]])
TENSOR

tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 1, 2, 3]],

        [[4, 5, 6, 7],
         [9, 0, 3, 2],
         [3, 3, 5, 3]]])

In [ ]:
TENSOR.size()

torch.Size([2, 3, 4])

##Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust thhose random numbers to better represent the data

In [ ]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2271, 0.1099, 0.1036, 0.6200],
        [0.4110, 0.3821, 0.7514, 0.8409],
        [0.1412, 0.9952, 0.3017, 0.4887]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))#hight, width, color channels(r,g,b)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and ones


In [ ]:
#Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###Creating a range of tensors and tensors-like

In [ ]:
#Use torch.range()
one_to_ten = torch.arange(0, 10, 2)
one_to_ten

tensor([0, 2, 4, 6, 8])

In [ ]:
#Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

##Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch
1.Tensors not right datatype
2.Tensors not right shape
3.Tensors not on the right device

In [ ]:
#Float 32 tensor
flaot_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #data type, float32, float16 ect
                               device='cpu', #can use cpu, gpu, cuda but you can do conversions between them
                               requires_grad=False)#track gradients with this tensor

flaot_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = flaot_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

#Getting attributes from tensors
###datatype - use tensor.dtype
###shape - use tensor.shape
###device - use tensor.device

#Manipulating Tensors (tensor operations)

###Tensor operations include:
*Addition
*Subtraction
*Multiplication(element-wise)
*division
*Matrix multiplication

In [ ]:
#create a tensor
tensor = torch.tensor([1,2,3])
tensor = tensor + 10

In [ ]:
#Multiply
tensor * 10

tensor([110, 120, 130])

In [ ]:
#Subtract
tensor - 10

tensor([1, 2, 3])

In [ ]:
#Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([110, 120, 130])

###Matrix multiplication



In [ ]:
#matrix multiplication
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])
torch.matmul(tensor1, tensor2) #can use @ too
#multiplication and addition

tensor(14)

#Shape errors
Matrix multiplication rules:Inner dimensions must match:Resulting matrix will have the shape of the outer dimensions

In [ ]:
#Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                          [9,12]])
#Use transpose to fix tensor
tensor_B = tensor_B.T#T is used to transpose a tensor

torch.mm(tensor_A, tensor_B)#mm is the same matmul



tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Finding the min,max, mean,sum,ect(tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#find the min
torch.min(x)

tensor(0)

In [ ]:
#find the max
torch.max(x)
x.max()

tensor(90)

In [ ]:
#needs to be floating point or long dtype
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

#Index of max and min
Use argmin and argmax

In [ ]:
x.argmax(), x.argmin()

(tensor(9), tensor(0))

##Reshaping, Stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shap
* View - Return a view of an input tensor of certain shape but keep the same memory
* Stacking - combine multiple tensors on top of each other(vstack) or side by side (hstack)
* Squeeze - remove all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view fo the input with dimensions permuted (swapped) in a certain way

In [ ]:
#Create tensor
import torch
x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
#Add an extra dimension
#dimensions of the reshape must maintain element values
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [ ]:
z = x.view(1,9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x, like a pointer. They are the same code just labled different

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)#dim0 is on top, dim1 is side by side
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [ ]:
#torch.squeeze() - removes all single dimensions from a target tensor
#turns tensor with shape 9,1 to shape 9
x_reshaped.squeeze().shape

torch.Size([3, 3])

In [ ]:
#torch.unsqueeze() - adds a single dim to a target tensor at a specific dim
#turns tensor with shape 9 to shape 9,1 or 1,9
x = x_reshaped.unsqueeze(dim=0)
x.shape

torch.Size([1, 3, 3])

In [ ]:

#torch.permute() changes the dims of a tensor in a specific way
x.permute(2,0,1).shape #rotates tensor dims to the right

torch.Size([3, 1, 3])

###Indexing
Similar to numpy

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x[0][0]#returns first row
x[0, 2, 2]#returns last element
x[0, :, 0]#returns the first row, : indexs all of dim 1

tensor([1, 4, 7])

In [ ]:
x[0,1,1:]

tensor([5, 6])

## PyTorch tensors & NumPy

Numpy is a popular scientific Python numerical computing library

* Data in NumPy, wnat in PyTorch tensor -> 'torch.from_numpy(ndarray)
* PyTorch tensor -> torch.Tensor.numpy()

In [ ]:
import torch
import numpy as np

array = np.arange(1,8)
tensor = torch.from_numpy(array)
array, tensor
#numpy default dtype is f64
#PyTorch default is f32

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [ ]:
array += 1
tensor
#tensor is a view of the array

tensor([2, 3, 4, 5, 6, 7, 8])

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor += 1
numpy_tensor
#These share memory, and are views of each other

array([2., 2., 2., 2., 2., 2., 2.], dtype=float32)

## Reproducibility (do it again)
* use torch.manual_seed(x) to set the random value to be consistent
* use np.random.seed(0) if using numpy

In [ ]:
import torch
rand_A = torch.rand(3,4)
rand_B = torch.rand(3,4)
print(rand_A == rand_B)
#Sudo random

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Need to set the seed after each random call, add flavor
torch.manual_seed(42)
rand_A = torch.rand(3,4)
torch.manual_seed(42)
rand_B = torch.rand(3,4)
print(rand_A)
print(rand_A == rand_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computations, thanks to CUDA + NVIDIA + PyTorch

## Getting a GPU

1. Use google Colab for free GPU
2. Use your own GPU
3. Use Cloud computing like Azure, AWS, GCP

In [ ]:
!nvidia-smi
#shows what Gpu you are currently working with


Tue Feb 27 03:08:36 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
### Check for GPU using pyTorch
import torch
torch.cuda.is_available()

True

## Setup device agnostic code

In [ ]:
#if gpu is available set it to cuda else cpu
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
torch.cuda.device_count()#Number of GPU's

1

## Putting tensors (and models on the GPU)

Allows for faster run times

In [ ]:
#Create a tensor (default on the cpu)
tensor = torch.tensor([1,2,3])
#tensor is on the cpu
#Uses agnostic code to transfer the tensor to the gpu, if not available keeps on cpu
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Numpy can only be used on the Cpu so you need to transfer back

In [ ]:
### 4. Moving tensors back to the cpu
tensor_on_cpu = tensor_on_gpu.to('cpu')
tensor_on_cpu.device

device(type='cpu')

In [ ]:
array = tensor_on_cpu.numpy()
array

array([1, 2, 3])

##Exercise

In [ ]:
import torch
tensor = torch.rand(7,7)
tensor

tensor([[0.0531, 0.6792, 0.3681, 0.5965, 0.5931, 0.5323, 0.4487],
        [0.4710, 0.5682, 0.4591, 0.5361, 0.5317, 0.7991, 0.1730],
        [0.3997, 0.2949, 0.7120, 0.5445, 0.4541, 0.9188, 0.9524],
        [0.0853, 0.5965, 0.6762, 0.5620, 0.2360, 0.2614, 0.0068],
        [0.8719, 0.6076, 0.9934, 0.6190, 0.6083, 0.4687, 0.9640],
        [0.2979, 0.9059, 0.4000, 0.2660, 0.8048, 0.6994, 0.6718],
        [0.4158, 0.9863, 0.5138, 0.3529, 0.5154, 0.4505, 0.6128]])

In [ ]:
new_tensor = torch.mm(tensor, torch.rand(1,7).T)
new_tensor

tensor([[1.7807],
        [1.7734],
        [2.3556],
        [1.2983],
        [3.0995],
        [2.2679],
        [2.1834]])

In [ ]:
torch.manual_seed(0)
tensor = torch.rand(7,7)
new_tensor = torch.mm(tensor, torch.rand(1,7).T)
new_tensor

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [ ]:
torch.cuda.manual_seed(1234)

In [ ]:
tensor = torch.rand(2,3)
tensor2 = torch.rand(2,3)
tensor.to('cuda')
tensor2.to('cuda')

tensor([[0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872]], device='cuda:0')

In [ ]:
tensormm = torch.mm(tensor, tensor2.T)


In [ ]:
tensormm.min()

tensor(0.5721)

In [ ]:
tensormm.max()

tensor(1.7488)

In [ ]:
tensormm.argmin()

tensor(3)

In [ ]:
tensormm.argmax()

tensor(0)

In [ ]:
torch.cuda.manual_seed(7)
tensor = torch.rand(1,1,1,10)
tensor, tensor.shape

(tensor([[[[0.6962, 0.5300, 0.2560, 0.7366, 0.0204, 0.2036, 0.3748, 0.2564,
            0.3251, 0.0902]]]]),
 torch.Size([1, 1, 1, 10]))

In [ ]:
new_tensor = tensor.squeeze()
new_tensor.shape, new_tensor

(torch.Size([10]),
 tensor([0.2952, 0.7967, 0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730,
         0.6186]))